// <auto-generated />
using System;
using Dse.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dse.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260604191630_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("Dse.Ingestion.IngestProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Checkpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DocsPerSecond")
                        .HasColumnType("REAL");

                    b.Property<TimeSpan>("Elapsed")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("EstimatedRemaining")
                        .HasColumnType("TEXT");

                    b.Property<long>("ManagedMemoryBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PercentComplete")
                        .HasColumnType("REAL");

                    b.Property<long>("Produced")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalToProduce")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WorkingMemoryBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("IngestProgress", (string)null);
                });

            modelBuilder.Entity("Dse.Ingestion.IngestRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveSourceKey")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DryRun")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActiveSourceKey")
                        .IsUnique()
                        .HasFilter("\"ActiveSourceKey\" IS NOT NULL");

                    b.HasIndex("SourceKey");

                    b.ToTable("IngestRun", (string)null);
                });

            modelBuilder.Entity("Dse.Sources.Source", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssemblyQualifiedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Source", (string)null);
                });

            modelBuilder.Entity("Dse.Ingestion.IngestProgress", b =>
                {
                    b.HasOne("Dse.Ingestion.IngestRun", "Run")
                        .WithMany("Phases")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Dse.Ingestion.IngestRun", b =>
                {
                    b.HasOne("Dse.Sources.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Dse.Ingestion.IngestRun", b =>
                {
                    b.Navigation("Phases");
                });
#pragma warning restore 612, 618
        }
    }
}
